sudo: required
language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
  - api/node_modules
  - lcms/node_modules
  - delivery/node_modules
  - qa/node_modules
  - "$TRAVIS_BUILD_DIR/google-cloud-sdk/"
before_install:
- yarn global add lerna
install:
- lerna bootstrap
before_script:
- lerna run test
script:
- lerna run build
before_deploy:
- chmod +x scripts/deploy.sh
- chmod +x api/scripts/deploy.sh
- chmod +x lcms/scripts/deploy.sh
- chmod +x delivery/scripts/deploy.sh
deploy:
  -  provider: script
     script: "./scripts/deploy.sh uat learn20-dev"
     on:
       branch: master
  -  provider: script
     script: "./scripts/deploy.sh dev learn20-dev"
     on:
       branch: development
after_deploy:
  - qa/node_modules/.bin/newman run qa/postman/Unity.postman_collection.json
  - qa/node_modules/.bin/cypress run qa/tests/cypress.json