sudo: required
language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
  - packages/api/node_modules
  - packages/lcms/node_modules
  - packages/delivery/node_modules
  - "$TRAVIS_BUILD_DIR/google-cloud-sdk/"
before_install:
- openssl aes-256-cbc -K $encrypted_a21a9babead1_key -iv $encrypted_a21a9babead1_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- yarn global add lerna
install:
- lerna bootstrap
script:
- lerna run build
before_deploy:
- tar -xzf credentials.tar.gz
deploy:
  provider: script
  script: "./scripts/deploy.sh"
  on:
    branch: master
