sudo: required
language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
  - packages/api/node_modules
  - packages/lcms/node_modules
  - packages/delivery/node_modules
  - "$TRAVIS_BUILD_DIR/google-cloud-sdk/"
before_install:
- yarn global add lerna
install:
- lerna bootstrap
before_script:
- lerna run test
script:
- lerna run build
before_deploy:
- openssl aes-256-cbc -K $encrypted_a21a9babead1_key -iv $encrypted_a21a9babead1_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
- chmod +x scripts/deploy.sh
- chmod +x packages/api/scripts/deploy.sh
- chmod +x packages/lcms/scripts/deploy.sh
- chmod +x packages/delivery/scripts/deploy.sh
deploy:
  -  provider: script
     script: "./scripts/deploy.sh uat"
     on:
       branch: master
  -  provider: script
     script: "./scripts/deploy.sh dev"
     on:
       branch: development
